### ISSUE TITLE
theme_urbn_map doesn't set Lato font for geom_text

### ISSUE THREAD

**Issue by sstrochak** [UI-Research/urbnthemes#34]
If you run `set_urbn_defaults("map")`, the labels will be in the correct font. But if you simply add `theme_urbn_map` to a plot, without setting any kind of Urban defaults before, the font will not be Lato on `geom_text` and `geom_text_repel` labels.

**Comment by awunderground** [comment]
`theme_urbn_map()` ([link](https://github.com/UI-Research/urbnthemes/blob/master/R/theme_urbn_map.R)) only changes styles that are controlled by `theme()`. I don't think there is an eloquent way to change default fonts with this function. 

`set_urbn_defaults()` ([link](https://github.com/UI-Research/urbnthemes/blob/master/R/set_urbn_defaults.R)) changes defaults with `theme()` and changes defaults that are not included in `theme()`. For example:

```
  # add Lato font to text and label geoms ---------------------------

  ggplot2::update_geom_defaults("text", list(family = "Lato"))
  ggplot2::update_geom_defaults("label", list(family = "Lato"))
  ggplot2::update_geom_defaults("text_repel", list(family = "Lato"))
  ggplot2::update_geom_defaults("label_repel", list(family = "Lato"))
```
So `update_geom_font_default()` is really a part of `set_urbn_defaults()`. @khueyama Is there value to writing this as its own function?

@sstrochak you know how to manually change the font in geom_text(), right?

**Comment by khueyama** [comment]
My thought is that the update_geom calls could be factored out into their own function(s) that are then called by `set_urbn_defaults` or on their own. Don't know how much value there is per say (if you're calling an `update_geom_font_default` function it seems like you'd be better of just calling `set_urbn_defaults`? Although maybe there is a use case where someone is making various plots that use `theme_urbn_map` for some and `theme_urbn_web for others`?), but it would address this issue.

**Comment by sstrochak** [comment]
@awunderground yes, I know how to manually change the font.

I usually prefer to use `theme_urbn_map()` on each map instead of setting the defaults because it's more flexible then setting the defaults- but also not a big deal just to call `set_urbn_defaults`. I never use `set_urbn_default(style = "map")` since I usually end up making some charts that aren't maps, and the map style strips the axes and labels.

**Comment by awunderground** [comment]
If you use `set_urbn_defaults()`, you can still use `theme_urbn_*()` to change the styles for individual plots/maps. 

I recommend  starting with `set_urbn_defaults(style = "print")` and then adding `theme_urbn_map()` to each map. 

I think this solves your issue @sstrochak and I think it eliminates the need for your change @khueyama. What do you think?

**Comment by sstrochak** [comment]
Yes, that works.
