### ISSUE TITLE
package installation issues

### ISSUE THREAD

**Issue by khueyama** [UI-Research/urbnthemes#51]
Have had a handful of package installation issues lately. Most recent example (R 3.4.4):
 - initially failed because `glue` was not installed (but we don't make use of glue - right?)
 - after glue was installed `devtools` then asked to update a bunch of packages (including `tibble` and a few others not relevant (I thought) to `urbnthemes`)
 - installation failed again on `Rcpp` - but `Rcpp` wasn't one of the packages listed in the update 
 - tried installing CRAN version of `Rcpp` - but got error message "could not remove prior installation of `Rcpp`
 - installed source version of `Rcpp` instead
 - finished what `devtools` wanted to update
 - finally installed `urbnthemes`  

No idea what is going on yet but it is very weird and frustrating (and tough to replicate!).

**Comment by awunderground** [comment]
@khueyama Can this issue be closed?

**Comment by khueyama** [comment]
Yeah, this seems to be weird behavior in `remotes`. I just tried again and this time it wanted me to update `rlang`(?) and `e1071` (???)
